version: '3.3'
services:

  balancer:
    build: ./nginx
    privileged: true
    volumes:
      - "./nginx/nginx2.conf:/etc/nginx/nginx.conf"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.j2"
    ports:
      - "127.0.0.1::80"
      - "127.0.0.1::443"
    command: /bin/bash -c "j2 /etc/nginx/conf.d/default.j2 > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - api
    logging:
      options:
        max-size: 1000m
    restart: 'no'

  postgres:
    image: postgres:10.0
    ports:
      - "5432"
    volumes:
      - "./data/postgres/etc:/etc/postgresql"
      - "./data/postgres/log:/var/log/postgresql"
      - "./data/postgres/postgresdb:/var/lib/postgresql/data"
      - "/var/run/postgresql:/var/run/postgresql"
    environment:
      POSTGRES_PASSWORD: UU6iyHsoTxAUznVgJDjewr8S
      POSTGRES_USER: admin
      POSTGRES_DB: spiti
      POSTGRES_HOST: /usr/src/postgresql
    logging:
      options:
        max-size: 1000m
    command: postgres -c work_mem="24MB"
    restart: 'no'

  api:
    build: ./api
    ports:
      - "127.0.0.1::3000"
    volumes:
      - "./api:/usr/src/app"
      - api_modules:/usr/src/app/node_modules/
      - "/var/run/postgresql:/usr/src/postgresql"
    environment:
      PRODUCTION_MODE: "OFF"
      POSTGRES_PASSWORD: UU6iyHsoTxAUznVgJDjewr8S
      POSTGRES_USER: admin
      POSTGRES_DB: spiti
      POSTGRES_HOST: /usr/src/postgresql
    depends_on:
      - postgres
      - redis
    logging:
      options:
        max-size: 1000m
    restart: 'no'

  redis:
    image: redis:alpine
    volumes:
      - "./data/redis:/data"
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
    logging:
      options:
        max-size: 1000m
    command: redis-server --requirepass 6fUrsxGqCmQjxhVTUX7UjAWGxVUZr8AvoroplRR8ZRB --appendonly yes
    restart: 'no'

volumes:
  api_modules:
  redis_socket:
