version: '3.3'
services:

  balancer:
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    environment:
      NGINX_HOST: "localhost"
      NGINX_SSL: "OFF"
      NGINX_PROD: "OFF"

  postgres:
    ports:
      - "5433:5432"
    environment:
      DEBUG: "true"

  api:
    tty: true
    environment:
      NODE_ENV: development
      domain: localhost
      protocol: http
      LOG_LEVEL: "debug"
    command: npm run development

  auth:
    tty: true
    environment:
      NODE_ENV: development
      domain: localhost
      protocol: http
      LOG_LEVEL: "debug"
    command: npm run development

  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.com
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
      - "./data/mailserver/mail:/var/mail"
      - "./data/mailserver/mail-state:/var/mail-state"
      - "./mailserver/:/tmp/docker-mailserver/"
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - PERMIT_DOCKER=host
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE

  redis:
    ports:
      - "127.0.0.1:6380:6379"
