version: '3.3'
services:

  balancer:
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_HOST: "spiti.clever-hosting.com"
      NGINX_SSL: "OFF"
      NGINX_PROD: "OFF"

  api:
    tty: true
    environment:
      NODE_ENV: production
      domain: spiti.clever-hosting.com
      protocol: http
      LOG_LEVEL: "debug"
      DEBUG: loopback:connector:postgresql,loopback:connector:mail,loopback:oauth2,loopback:security:acl,oauth2orize
    command: npm start

  auth:
    tty: true
    environment:
      NODE_ENV: production
      domain: spiti.clever-hosting.com
      protocol: http
      LOG_LEVEL: "debug"
      DEBUG: loopback:connector:postgresql,loopback:connector:mail,loopback:oauth2,loopback:security:acl,oauth2orize
    command: npm start
