version: '3.3'
services:

  api:
    volumes:
      - "./data/storage_test:/usr/src/storage_test"
    environment:
      POSTGRES_DB_TEST: spiti_test
      NODE_ENV: test
      DEBUG: ''
    command: npm run test:dev

  auth:
    volumes:
      - "./api/sequelize:/usr/src/app/sequelize"
    environment:
      POSTGRES_DB_TEST: spiti_auth_test
      NODE_ENV: test
    command: npm run test:dev
