version: '3.3'
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
services:

  balancer:
    build: ./nginx
    networks:
      backend:
        ipv4_address: 10.5.0.2
    privileged: true
    volumes:
      - "./nginx/nginx2.conf:/etc/nginx/nginx.conf"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.j2"
      - "./data/storage/public:/uploads-public"
      - "./nginx/pass/explorer.txt:/etc/nginx/passwords/explorer.txt"
    ports:
      - "127.0.0.1::80"
      - "127.0.0.1::443"
    command: /bin/bash -c "j2 /etc/nginx/conf.d/default.j2 > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - api
    logging:
      options:
        max-size: 1000m
    restart: 'no'

  postgres:
    image: postgres:10.0
    networks:
      backend:
          ipv4_address: 10.5.0.11
    ports:
      - "5432"
    volumes:
      - "./data/postgres/etc:/etc/postgresql"
      - "./data/postgres/log:/var/log/postgresql"
      - "./data/postgres/postgresdb:/var/lib/postgresql/data"
      - "/var/run/postgresql:/var/run/postgresql"
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: spiti,spiti_test
      POSTGRES_PASSWORD: UU6iyHsoTxAUznVgJDjewr8S
      POSTGRES_USER: admin
      POSTGRES_HOST: postgres
    logging:
      options:
        max-size: 1000m
    command: postgres -c work_mem="24MB"
    restart: 'no'

  api:
    build: ./api
    user: "${UID}:${GID}"
    networks:
      backend:
        ipv4_address: 10.5.0.3
    ports:
      - "127.0.0.1::3000"
    volumes:
      - "./api:/usr/src/app"
      - api_modules:/usr/src/app/node_modules/
      - "/var/run/postgresql:/usr/src/postgresql"
      - "./data/storage:/usr/src/storage"
    environment:
      PRODUCTION_MODE: "OFF"
      POSTGRES_PASSWORD: UU6iyHsoTxAUznVgJDjewr8S
      POSTGRES_USER: admin
      POSTGRES_DB: spiti
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 6fUrsxGqCmQjxhVTUX7UjAWGxVUZr8AvoroplRR8ZRB
      baseSchema: spiti
    depends_on:
      - postgres
      - redis
    logging:
      options:
        max-size: 1000m
    restart: 'no'

  auth:
    build: ./auth
    user: "${UID}:${GID}"
    networks:
      backend:
         ipv4_address: 10.5.0.4
    ports:
      - "127.0.0.1::3000"
    volumes:
      - "./auth:/usr/src/app"
      - auth_modules:/usr/src/app/node_modules/
      - "/var/run/postgresql:/usr/src/postgresql"
    environment:
      PRODUCTION_MODE: "OFF"
      POSTGRES_PASSWORD: UU6iyHsoTxAUznVgJDjewr8S
      POSTGRES_USER: admin
      POSTGRES_DB: spiti
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
      - redis
    logging:
      options:
        max-size: 1000m
    restart: 'no'

  redis:
    image: redis:alpine
    networks:
      backend:
        ipv4_address: 10.5.0.5
    volumes:
      - "./data/redis:/data"
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
    logging:
      options:
        max-size: 1000m
    command: redis-server --requirepass 6fUrsxGqCmQjxhVTUX7UjAWGxVUZr8AvoroplRR8ZRB 
    restart: 'no'

volumes:
  api_modules:
  auth_modules:
  redis_socket:
