version: '3.3'
services:

  balancer:
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    environment:
      NGINX_HOST: "localhost"
      NGINX_SSL: "OFF"
      NGINX_PROD: "OFF"

  postgres:
    ports:
      - "5433:5432"
    environment:
      DEBUG: "true"

  api:
    tty: true
    environment:
      NODE_ENV: development
      domain: localhost
      protocol: http
      LOG_LEVEL: "debug"
    command: npm run development

  redis:
    ports:
      - "127.0.0.1:6380:6379"
